
lang_list = ['ar', 'bg', 'ca', 'hr', 'zh-Hans', 'zh-Hant', 'cs', 'da','nl',
             'en', 'fil', 'fi', 'fr', 'de', 'el', 'he', 'hi', 'hu', 'id', 'it',
             'ja', 'ko', 'lv', 'lt', 'no', 'pl', 'pt', 'ro', 'ru', 'sr', 'sk',
             'sl', 'es', 'sv', 'th', 'tr', 'uk', 'vi', None]

country_list = ['com', 'ac', 'ad', 'ae', 'af', 'ag', 'ai', 'al', 'am','ao',
                'ar', 'as', 'at', 'au', 'az', 'ba', 'bd', 'be', 'bf', 'bg',
                'bh', 'bi', 'bj', 'bn', 'bo', 'br', 'bs', 'bt', 'bw', 'by',
                'bz', 'ca', 'kh', 'cc', 'cd', 'cf', 'cat','cg', 'ch', 'ci',
                'ck', 'cl', 'cm', 'cn', 'co', 'cr', 'cu', 'cv', 'cy', 'cz',
                'de', 'dj', 'dk', 'dm', 'do', 'dz', 'ec', 'ee', 'eg', 'es',
                'et', 'fi', 'fj', 'fm', 'fr', 'ga', 'ge', 'gf', 'gg', 'gh',
                'gi', 'gl', 'gm', 'gp', 'gr', 'gt', 'gy', 'hk', 'hn', 'hr',
                'ht', 'hu', 'id', 'iq', 'ie', 'il', 'im', 'in', 'io', 'is',
                'it', 'je', 'jm', 'jo', 'jp', 'ke', 'ki', 'kg', 'kr', 'kw',
                'kz', 'la', 'lb', 'lc', 'li', 'lk', 'ls', 'lt', 'lu', 'lv',
                'ly', 'ma', 'md', 'me', 'mg', 'mk', 'ml', 'mm', 'mn', 'ms',
                'mt', 'mu', 'mv', 'mw', 'mx', 'my', 'mz', 'na', 'ne', 'nf',
                'ng', 'ni', 'nl', 'no', 'np', 'nr', 'nu', 'nz', 'om', 'pk',
                'pa', 'pe', 'ph', 'pl', 'pg', 'pn', 'pr', 'ps', 'pt', 'py',
                'qa', 'ro', 'rs', 'ru', 'rw', 'sa', 'sb', 'sc', 'se', 'sg',
                'sh', 'si', 'sk', 'sl', 'sn', 'sm', 'so', 'st', 'sr', 'sv',
                'td', 'tg', 'th', 'tj', 'tk', 'tl', 'tm', 'to', 'tn', 'tr',
                'tt', 'tw', 'tz', 'ua', 'ug', 'uk', 'us', 'uy', 'uz', 'vc',
                've', 'vg', 'vi', 'vn', 'vu', 'ws', 'za', 'zm', 'zw', None]


stopwords_en = ["i","me","my","myself","we","our","ours","ourselves",
                "you","your","yours","yourself","yourselves","he","him",
                "his","himself","she","her","hers","herself","it","its",
                "itself","they","them","their","theirs","themselves",
                "what","which","who","whom","this","that","these","those",
                "am","is","are","was","were","be","been","being","have",
                "has","had","having","do","does","did","doing","would",
                "should","could","ought","i'm","you're","he's","she's",
                "it's","we're","they're","i've","you've","we've","they've",
                "i'd","you'd","he'd","she'd","we'd","they'd","i'll",
                "you'll","he'll","she'll","we'll","they'll","isn't",
                "aren't","wasn't","weren't","hasn't","haven't","hadn't",
                "doesn't","don't","didn't","won't","wouldn't","shan't",
                "shouldn't","can't","cannot","couldn't","mustn't","let's",
                "that's","who's","what's","here's","there's","when's",
                "where's","why's","how's","a","an","the","and","but","if",
                "or","because","as","until","while","of","at","by","for",
                "with","about","against","between","into","through",
                "during","before","after","above","below","to","from",
                "up","down","in","out","on","off","over","under","again",
                "further","then","once","here","there","when","where",
                "why","how","all","any","both","each","few","more","most",
                "other","some","such","no","nor","not","only","own","same",
                "so","than","too","very"]


# stopwords_ar = ["‫.‬", "،", "عدد", "عدة", "عن", "عند", "عندما", "على", "عليه",
#                "عليها", "تم", "ضد", "بعد", "بعض", "بسبب", "حتى", "اذا", "احد",
#                "اثر", "غدا", "اطار", "اربعة", "اخرى", "بان", "اجل", "غير", "بشكل",
#                "حاليا", "بن", "به", "ثم", "ان", "او", "اي", "بها", "حيث",
#                "اكد", "الا", "اما", "التى", "التي", "اكثر", "ايضا", "الذاتي" "الذى",
#                "الذي", "الان", "خلال", "حوالى", "الذين", "بين", "ذلك", "دون", "حول",
#                "حين", "الى", "انه", "ضمن", "انها", "جميع", "اليوم", "و", "قد",
#                "لا", "ما", "مع", "فان", "قبل", "قال", "كان", "لدى", "نحو",
#                "هذه", "وان", "واكد", "كانت", "فى", "في", "كل", "لم", "لن",
#                "له", "من", "هو", "هي", "كما", "لها", "منذ", "وقد", "ولا",
#                "هناك", "وكان", "وقالت", "وكانت", "فيه", "لكن", "وفي", "وقف", "ولم",
#                "ومن", "وهو", "وهي", "يوم", "فيها", "منها", "يكون", "يمكن"]
